---
# we use docker as plateform
driver:
  name: docker
  privileged: true
  volume: /sys/fs/cgroup:/sys/fs/cgroup
  provision_command:
    - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config

# Ansible will be our provisioner
provisioner:
  name: ansible_playbook
  hosts: localhost
  require_chef_for_busser: false
  require_ruby_for_busser: false
  require_ansible_omnibus: false
  idempotency_test: true

# We use Inspec as testing framework
verifier:
  name: inspec
  inspec_tests:
    - path: tests/inspec

platforms:
  # Centos
  - name: centos-8
    driver:
      image: diodonfrost/centos-8-ansible
      platform: centos
  - name: centos-7
    driver:
      image: diodonfrost/centos-7-ansible
      platform: centos
  - name: centos-6
    driver:
      image: diodonfrost/centos-6-ansible
      platform: centos

  # Fedora
  - name: fedora-30
    driver:
      image: diodonfrost/fedora-30-ansible
      platform: centos
  - name: fedora-29
    driver:
      image: diodonfrost/fedora-29-ansible
      platform: centos
  - name: fedora-28
    driver:
      image: diodonfrost/fedora-28-ansible
      platform: centos
  - name: fedora-27
    driver:
      image: diodonfrost/fedora-27-ansible
      platform: centos
  - name: fedora-26
    driver:
      image: diodonfrost/fedora-26-ansible
      platform: centos

  # Ubuntu
  - name: ubuntu-20.04
    driver:
      image: diodonfrost/ubuntu-20.04-ansible
      platform: ubuntu
  - name: ubuntu-18.04
    driver:
      image: diodonfrost/ubuntu-18.04-ansible
      platform: ubuntu
  - name: ubuntu-16.04
    driver:
      image: diodonfrost/ubuntu-16.04-ansible
      platform: ubuntu
  - name: ubuntu-14.04
    driver:
      image: ubuntu:14.04
      platform: ubuntu

  # Debian
  - name: debian-10
    driver:
      image: diodonfrost/debian-10-ansible
      platform: debian
  - name: debian-9
    driver:
      image: diodonfrost/debian-9-ansible
      platform: debian
  - name: debian-8
    driver:
      image: diodonfrost/debian-8-ansible
      platform: debian

  # Oraclelinux
  - name: oraclelinux-8
    driver:
      image: diodonfrost/oraclelinux-8-ansible
      platform: centos
  - name: oraclelinux-7
    driver:
      image: diodonfrost/oraclelinux-7-ansible
      platform: centos
  - name: oraclelinux-6
    driver:
      image: diodonfrost/oraclelinux-6-ansible
      platform: centos

  # Amazonlinux
  - name: amazonlinux-2
    driver:
      image: diodonfrost/amazonlinux-2-ansible
      platform: centos
  - name: amazonlinux-1
    driver:
      image: diodonfrost/amazonlinux-1-ansible
      platform: centos

# Define playbook
suites:
  - name: mariadb-10.4
    provisioner:
      name: ansible_playbook
      playbook: tests/test.yml
      extra_vars:
        mariadb_version: "10.4"
    excludes:
      - oraclelinux-7-ansible
      - amazonlinux-2-ansible
      - fedora-27-ansible
  - name: mariadb-10.3
    provisioner:
      name: ansible_playbook
      playbook: tests/test.yml
      extra_vars:
        mariadb_version: "10.3"
    excludes:
      - oraclelinux-7-ansible
      - amazonlinux-2-ansible
      - fedora-27-ansible
  - name: mariadb-10.2
    provisioner:
      name: ansible_playbook
      playbook: tests/test.yml
      extra_vars:
        mariadb_version: "10.2"
    excludes:
      - oraclelinux-7-ansible
      - amazonlinux-2-ansible
  - name: mariadb-10.1
    provisioner:
      name: ansible_playbook
      playbook: tests/test.yml
      extra_vars:
        mariadb_version: "10.1"
    excludes:
      - fedora-27-ansible
      - oraclelinux-7-ansible
      - amazonlinux-2-ansible
  - name: mariadb-10.0
    provisioner:
      name: ansible_playbook
      playbook: tests/test.yml
      extra_vars:
        mariadb_version: "10.0"
    excludes:
      - fedora-28-ansible
      - fedora-27-ansible
      - ubuntu-18.04-ansible
      - ubuntu-17.10-ansible
      - debian-9-ansible
      - oraclelinux-7-ansible
      - amazonlinux-2-ansible
      - opensuse-42.3-ansible
      - opensuse-42.2-ansible
  - name: os-packaging
    provisioner:
      name: ansible_playbook
      playbook: tests/test.yml
      extra_vars:
        install_from: os_repository
    includes:
      - oraclelinux-7-ansible
      - amazonlinux-2-ansible
