---
# Install and configure mariadb

- name: Update apt cache
  apt:
    update_cache: yes
  changed_when: false
  when: ansible_os_family == "Debian"

- name: Mariadb install
  package:
    name: "{{ mariadb_package }}"
    state: present

- name: Mariadb service
  service:
    name: "{{ mariadb_service }}"
    state: started
    enabled: yes
