name: CI

on:
  push:
  schedule:
    - cron: '0 18 * * sun'

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - centos-8
          - centos-7
          - centos-6
          - fedora-31
          - fedora-30
          - fedora-29
          - fedora-28
          - fedora-27
          - ubuntu-18.04
          - ubuntu-16.04
          - ubuntu-14.04
          - debian-10
          - debian-9
          - debian-8
          - opensuse-15
          - opensuse-42.3
        playbook:
          - mariadb-10.5
          - mariadb-10.4
          - mariadb-10.3
        exclude:
          - {distribution: "centos-6", playbook: "mariadb-10.5"}
        include:
          - {distribution: "oraclelinux-7", playbook: "os_repository"}
          - {distribution: "amazonlinux-2", playbook: "os_repository"}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Disable apparmor
        run: sudo systemctl stop apparmor

      - name: Install Inspec
        run: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec -v 4.18.51

      - name: Test Ansible role Mariadb
        run: |
          container_id=$(mktemp)
          sudo apparmor_status

          # Run container and mount ansible role with it
          sudo docker run --detach --security-opt apparmor=unconfined --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/ansible-role-mariadb:ro diodonfrost/${{ matrix.distribution }}-ansible:latest > "${container_id}"

          # Check syntax
          sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-mariadb/tests/playbooks/${{ matrix.playbook }}.yml --syntax-check

          # Run ansible playbook
          sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-mariadb/tests/playbooks/${{ matrix.playbook }}.yml

          # Test indempotence
          sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-mariadb/tests/playbooks/${{ matrix.playbook }}.yml \
          | grep -q 'changed=0.*failed=0' \
          && (echo 'Idempotence test: pass' && exit 0) \
          || (echo 'Idempotence test: fail' && exit 1)

          # Test role
          inspec exec tests/inspec --chef-license accept-silent -t docker://$(cat ${container_id})
